sudo: false
language: node_js
branches:
  only:
  - master
  - dev
node_js:
- '8'
before_script:
- npm install
script:
- npm run build
deploy:
  provider: gae
  keyfile: distense-ui-a989f6f0ddf6.json.enc
  project: '202207115572'
before_install:
- openssl aes-256-cbc -K $encrypted_54eebe5abc9c_key -iv $encrypted_54eebe5abc9c_iv
  -in distense-ui-a989f6f0ddf6.json.enc -out ~\/Downloads/distense-ui-a989f6f0ddf6.json
  -d
